vich_uploader:
    db_driver: orm

    mappings:
        imagens_artigos:
            uri_prefix: /imagens/artigos
            upload_destination: '%kernel.project_dir%/public/imagens/artigos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
